version: '3.8'

services:
  shortner:
    build: ../../
    command: ./shortner
    hostname: localhost
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_DB=2
    command: [ "redis-server", "--requirepass", "admin", "--databases", "16", "--maxmemory", "2gb", "--maxmemory-policy", "allkeys-lru" ]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: